// Code generated by "stringer -type=blobKind -linecomment"; DO NOT EDIT.

package azblob

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknownBlobKind-0]
	_ = x[entryBlob-1]
	_ = x[objectBlob-2]
}

const _blobKind_name = "UnknownEntryObject"

var _blobKind_index = [...]uint8{0, 7, 12, 18}

func (i blobKind) String() string {
	idx := int(i) - 0
	if idx >= len(_blobKind_index)-1 {
		return "blobKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _blobKind_name[_blobKind_index[idx]:_blobKind_index[idx+1]]
}
