// Code generated by "stringer -type=FailureReason"; DO NOT EDIT.

package workflow

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FRUnknown-0]
	_ = x[FRPreCheck-100]
	_ = x[FRBlock-200]
	_ = x[FRPostCheck-300]
	_ = x[FRContCheck-400]
	_ = x[FRStopped-500]
}

const (
	_FailureReason_name_0 = "FRUnknown"
	_FailureReason_name_1 = "FRPreCheck"
	_FailureReason_name_2 = "FRBlock"
	_FailureReason_name_3 = "FRPostCheck"
	_FailureReason_name_4 = "FRContCheck"
	_FailureReason_name_5 = "FRStopped"
)

func (i FailureReason) String() string {
	switch {
	case i == 0:
		return _FailureReason_name_0
	case i == 100:
		return _FailureReason_name_1
	case i == 200:
		return _FailureReason_name_2
	case i == 300:
		return _FailureReason_name_3
	case i == 400:
		return _FailureReason_name_4
	case i == 500:
		return _FailureReason_name_5
	default:
		return "FailureReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
