// Code generated by "stringer -type=ObjectType"; DO NOT EDIT.

package workflow

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OTUnknown-0]
	_ = x[OTPlan-1]
	_ = x[OTCheck-2]
	_ = x[OTBlock-5]
	_ = x[OTSequence-6]
	_ = x[OTAction-7]
}

const (
	_ObjectType_name_0 = "OTUnknownOTPlanOTCheck"
	_ObjectType_name_1 = "OTBlockOTSequenceOTAction"
)

var (
	_ObjectType_index_0 = [...]uint8{0, 9, 15, 22}
	_ObjectType_index_1 = [...]uint8{0, 7, 17, 25}
)

func (i ObjectType) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _ObjectType_name_0[_ObjectType_index_0[i]:_ObjectType_index_0[i+1]]
	case 5 <= i && i <= 7:
		i -= 5
		return _ObjectType_name_1[_ObjectType_index_1[i]:_ObjectType_index_1[i+1]]
	default:
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
