// Code generated by "stringer -type=WhenDeferred -linecomment -valid -invalid=0"; DO NOT EDIT.

package workflow

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WhenUnknown-0]
	_ = x[OnSuccess-1]
	_ = x[OnFailure-2]
	_ = x[Always-3]
}

const _WhenDeferred_name = "UnknownOnSuccessOnFailureAlways"

var _WhenDeferred_index = [...]uint8{0, 7, 16, 25, 31}

func (i WhenDeferred) String() string {
	idx := int(i) - 0
	if idx >= len(_WhenDeferred_index)-1 {
		return "WhenDeferred(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WhenDeferred_name[_WhenDeferred_index[idx]:_WhenDeferred_index[idx+1]]
}

func (i WhenDeferred) Valid() bool {
	if i == 0 {
		return false
	}
	idx := int(i) - 0
	if idx >= len(_WhenDeferred_index)-1 {
		return false
	}
	return true
}
