// Code generated by "stringer -type=Type"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Plan-1]
	_ = x[Block-2]
	_ = x[Checks-3]
	_ = x[Sequence-4]
	_ = x[Action-5]
}

const _Type_name = "UnknownPlanBlockChecksSequenceAction"

var _Type_index = [...]uint8{0, 7, 11, 16, 22, 30, 36}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
