// Code generated by "stringer -type=ChecksType -trimprefix=CT -valid -invalid=0"; DO NOT EDIT.

package builder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CTUnknown-0]
	_ = x[PreChecks-1]
	_ = x[ContChecks-2]
	_ = x[PostChecks-3]
	_ = x[BypassChecks-4]
	_ = x[DeferredChecks-5]
}

const _ChecksType_name = "UnknownPreChecksContChecksPostChecksBypassChecksDeferredChecks"

var _ChecksType_index = [...]uint8{0, 7, 16, 26, 36, 48, 62}

func (i ChecksType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ChecksType_index)-1 {
		return "ChecksType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChecksType_name[_ChecksType_index[idx]:_ChecksType_index[idx+1]]
}

func (i ChecksType) Valid() bool {
	if i == 0 {
		return false
	}
	idx := int(i) - 0
	if i < 0 || idx >= len(_ChecksType_index)-1 {
		return false
	}
	return true
}
