// Code generated by "stringer -type=DeferCondition -trimprefix=DC -valid -invalid=0"; DO NOT EDIT.

package builder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DCUnknown-0]
	_ = x[OnSuccess-1]
	_ = x[OnFailure-2]
}

const _DeferCondition_name = "UnknownOnSuccessOnFailure"

var _DeferCondition_index = [...]uint8{0, 7, 16, 25}

func (i DeferCondition) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DeferCondition_index)-1 {
		return "DeferCondition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeferCondition_name[_DeferCondition_index[idx]:_DeferCondition_index[idx+1]]
}

func (i DeferCondition) Valid() bool {
	if i == 0 {
		return false
	}
	idx := int(i) - 0
	if i < 0 || idx >= len(_DeferCondition_index)-1 {
		return false
	}
	return true
}
