name: Go

on:
  push: # Every branch, including those with an open PR.
  workflow_dispatch: # This allows manual triggering of the workflow

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  govulncheck_job:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
        with:
          # Empty so setup-go uses go-version-file; a version input would take precedence over it.
          go-version-input: ""
          go-version-file: go.mod
          go-package: ./...
